databases:
- name: posthog
  databaseName: posthog
  user: posthog
  plan: standard # PostHog can quickly use up hundreds of MBs of disk space, depending on the volume of analytics
  region: frankfurt

services:
- type: web
  name: posthog
  env: docker
  region: frankfurt
  dockerfilePath: ./server/Dockerfile
  dockerContext: ./server
  autoDeploy: false
  envVars:
  - key: IS_BEHIND_PROXY
    value: 1
  - key: IS_DOCKER
    value: true
  - key: POSTHOG_REDIS_HOST
    fromService:
      name: posthog-redis
      type: pserv
      property: host
  - key: POSTHOG_REDIS_PORT
    fromService:
      name: posthog-redis
      type: pserv
      property: port
  - key: DATABASE_URL
    fromDatabase:
      name: posthog
      property: connectionString
  - key: SECRET_KEY
    generateValue: true
  - key: DEPLOYMENT
    value: render

- type: pserv
  region: frankfurt
  name: posthog-redis
  env: docker
  autoDeploy: false
  repo: https://github.com/render-examples/redis.git
  disk:
    name: data
    mountPath: /var/lib/redis
    sizeGB: 10

- type: worker
  region: frankfurt
  name: posthog-worker
  env: docker
  dockerfilePath: ./worker/Dockerfile
  dockerContext: ./worker
  numInstances: 1
  autoDeploy: false
  envVars:
  - key: POSTHOG_REDIS_HOST
    fromService:
      name: posthog-redis
      type: pserv
      property: host
  - key: POSTHOG_REDIS_PORT
    fromService:
      name: posthog-redis
      type: pserv
      property: port
  - key: DATABASE_URL
    fromDatabase:
      name: posthog
      property: connectionString
  - key: IS_DOCKER
    value: true
  - key: SECRET_KEY
    generateValue: true
  - key: DEPLOYMENT
    value: render

- type: worker
  region: frankfurt
  name: posthog-plugin-server
  env: docker
  dockerfilePath: ./plugin-server/Dockerfile
  dockerContext: ./plugin-server
  numInstances: 1
  autoDeploy: false
  envVars:
  - key: POSTHOG_REDIS_HOST
    fromService:
      name: posthog-redis
      type: pserv
      property: host
  - key: POSTHOG_REDIS_PORT
    fromService:
      name: posthog-redis
      type: pserv
      property: port
  - key: DATABASE_URL
    fromDatabase:
      name: posthog
      property: connectionString
  - key: DEPLOYMENT
    value: render
